! Lightweight companion to dataframe_index_date.f90 for xp2f.py's
! pd.DataFrame({"col1": arr1, "col2": arr2, ...}, index=str_labels) support --
! a DataFrame whose row index is a plain string label (e.g. a component
! name), not a date. Deliberately minimal: only what xmix.py-style code
! needs (construction from named real-array columns, subtraction between
! two same-shape frames, and printing) -- see dataframe_index_date.f90 for
! the much larger date-indexed sibling this mirrors the nrow/ncol/operator(-)
! naming conventions of.
module dataframe_str_index_mod
   use, intrinsic :: iso_fortran_env, only: dp => real64
   use, intrinsic :: ieee_arithmetic, only: ieee_value, ieee_quiet_nan
   implicit none
   private

   integer, parameter :: nlen_label_str = 64
   integer, parameter :: nlen_columns_str = 64

   type, public :: DataFrame_str_index
      character(len=nlen_label_str), allocatable :: index(:)
      character(len=nlen_columns_str), allocatable :: columns(:)
      real(kind=dp), allocatable :: values(:, :)
   contains
      procedure :: display => display_str_index
      procedure :: col_pos => col_pos_str
      procedure :: cumsum => cumsum_str
      procedure :: cumprod => cumprod_str
      procedure :: diff => diff_str
      procedure :: abs => abs_str
      procedure :: sort_values => sort_values_str
      procedure :: T => transpose_str
   end type DataFrame_str_index

   public :: nrow, ncol, abs_str, log_df_str, exp_df_str, append_col_str
   public :: operator(+), operator(-), operator(*), operator(/)

   interface operator(+)
      module procedure add_df_df_str, add_df_scalar_str, add_scalar_df_str
   end interface

   interface operator(-)
      module procedure subtract_df_df_str, subtract_df_scalar_str, subtract_scalar_df_str
   end interface

   interface operator(*)
      module procedure multiply_df_df_str, multiply_df_scalar_str, multiply_scalar_df_str
   end interface

   interface operator(/)
      module procedure divide_df_df_str, divide_df_scalar_str, divide_scalar_df_str
   end interface

contains

   elemental function nrow(df) result(num_rows)
      type(DataFrame_str_index), intent(in) :: df
      integer :: num_rows
      if (allocated(df%values)) then
         num_rows = size(df%values, 1)
      else
         num_rows = -1
      end if
   end function nrow

   elemental function ncol(df) result(num_col)
      type(DataFrame_str_index), intent(in) :: df
      integer :: num_col
      if (allocated(df%values)) then
         num_col = size(df%values, 2)
      else
         num_col = -1
      end if
   end function ncol

   pure function col_pos_str(self, column) result(jcol)
      ! return the column position (1..ncol) for column name -- ported from
      ! dataframe_index_date.f90's col_pos, needed so df["col"] reads
      ! generated by xp2f.py's generic `%values(:, %col_pos(...))` codegen
      ! (see _pandas_df_vars) work for DataFrame_str_index too.
      class(DataFrame_str_index), intent(in) :: self
      character(len=*), intent(in) :: column
      integer :: jcol
      jcol = findloc(self%columns, column, dim=1)
      if (jcol == 0) error stop "in col_pos, column not found: "//trim(column)
   end function col_pos_str

   subroutine append_col_str(self, column, col_values)
      ! Grow %values/%columns by one column at runtime -- used by
      ! xp2f.py's df["new_col"] = expr codegen for a genuinely NEW
      ! column (as opposed to overwriting an existing one, a plain slot
      ! write). Deliberately a real runtime append rather than assuming
      ! the final column count is already known/pre-allocated: the
      ! caller may print or otherwise use self between construction and
      ! this call, and that use must see only the columns that exist so
      ! far, not ones a later statement will add.
      class(DataFrame_str_index), intent(inout) :: self
      character(len=*), intent(in) :: column
      real(kind=dp), intent(in) :: col_values(:)
      real(kind=dp), allocatable :: vtmp(:, :)
      character(len=nlen_columns_str), allocatable :: ctmp(:)
      integer :: n, ncol0
      n = size(col_values)
      if (.not. allocated(self%values)) then
         allocate (self%values(n, 1))
         self%values(:, 1) = col_values
         self%columns = [column]
         return
      end if
      ncol0 = size(self%values, 2)
      allocate (vtmp(n, ncol0 + 1))
      vtmp(:, 1:ncol0) = self%values
      vtmp(:, ncol0 + 1) = col_values
      call move_alloc(vtmp, self%values)
      allocate (ctmp(ncol0 + 1))
      ctmp(1:ncol0) = self%columns
      ctmp(ncol0 + 1) = column
      call move_alloc(ctmp, self%columns)
   end subroutine append_col_str

   pure function cumsum_str(self) result(df_new)
      ! cumulative sum down each column
      class(DataFrame_str_index), intent(in) :: self
      type(DataFrame_str_index) :: df_new
      integer :: i
      df_new%index = self%index
      df_new%columns = self%columns
      df_new%values = self%values
      do i = 2, nrow(self)
         df_new%values(i, :) = df_new%values(i - 1, :) + df_new%values(i, :)
      end do
   end function cumsum_str

   pure function cumprod_str(self) result(df_new)
      ! cumulative product down each column
      class(DataFrame_str_index), intent(in) :: self
      type(DataFrame_str_index) :: df_new
      integer :: i
      df_new%index = self%index
      df_new%columns = self%columns
      df_new%values = self%values
      do i = 2, nrow(self)
         df_new%values(i, :) = df_new%values(i - 1, :)*df_new%values(i, :)
      end do
   end function cumprod_str

   pure function diff_str(self, periods) result(df_new)
      ! row-to-row difference `periods` rows apart (NaN-filled for the
      ! first `periods` rows, matching pandas' df.diff()).
      class(DataFrame_str_index), intent(in) :: self
      integer, intent(in), optional :: periods
      type(DataFrame_str_index) :: df_new
      integer :: p, nr, nc
      p = 1
      if (present(periods)) p = periods
      nr = nrow(self)
      nc = ncol(self)
      df_new%index = self%index
      df_new%columns = self%columns
      allocate (df_new%values(nr, nc))
      df_new%values = ieee_value(0.0_dp, ieee_quiet_nan)
      if (p > 0 .and. p < nr) then
         df_new%values(p + 1:nr, :) = self%values(p + 1:nr, :) - self%values(1:nr - p, :)
      end if
   end function diff_str

   pure function abs_str(self) result(df_new)
      class(DataFrame_str_index), intent(in) :: self
      type(DataFrame_str_index) :: df_new
      df_new%index = self%index
      df_new%columns = self%columns
      df_new%values = abs(self%values)
   end function abs_str

   pure function transpose_str(self) result(df_new)
      ! df.T -- swap rows/columns; symmetric for this type since both the
      ! index and columns are already plain strings.
      class(DataFrame_str_index), intent(in) :: self
      type(DataFrame_str_index) :: df_new
      df_new%index = self%columns
      df_new%columns = self%index
      df_new%values = transpose(self%values)
   end function transpose_str

   subroutine argsort_real_str(a, perm, ascending)
      ! bottom-up merge argsort -- local copy of dataframe_index_date.f90's
      ! argsort_index, specialized to plain reals instead of type(date), so
      ! this file stays dependency-free (see the header note).
      real(kind=dp), intent(in) :: a(:)
      integer, allocatable, intent(out) :: perm(:)
      logical, intent(in) :: ascending
      integer :: n, width, i, left, mid, right, p, q, k
      integer, allocatable :: tmp(:)
      n = size(a)
      allocate (perm(n), tmp(n))
      perm = [(i, i=1, n)]
      width = 1
      do while (width < n)
         i = 1
         do while (i <= n)
            left = i
            mid = min(i + width - 1, n)
            right = min(i + 2*width - 1, n)
            p = left; q = mid + 1; k = left
            do while (p <= mid .and. q <= right)
               if (ascending) then
                  if (a(perm(p)) <= a(perm(q))) then
                     tmp(k) = perm(p); p = p + 1
                  else
                     tmp(k) = perm(q); q = q + 1
                  end if
               else
                  if (a(perm(p)) >= a(perm(q))) then
                     tmp(k) = perm(p); p = p + 1
                  else
                     tmp(k) = perm(q); q = q + 1
                  end if
               end if
               k = k + 1
            end do
            do while (p <= mid)
               tmp(k) = perm(p); p = p + 1; k = k + 1
            end do
            do while (q <= right)
               tmp(k) = perm(q); q = q + 1; k = k + 1
            end do
            perm(left:right) = tmp(left:right)
            i = i + 2*width
         end do
         width = 2*width
      end do
   end subroutine argsort_real_str

   subroutine sort_values_str(self, by, ascending)
      ! sort rows by a column's values, permuting the index accordingly.
      class(DataFrame_str_index), intent(inout) :: self
      character(len=*), intent(in) :: by
      logical, intent(in), optional :: ascending
      logical :: asc
      integer :: n, jcol
      integer, allocatable :: perm(:)
      real(kind=dp), allocatable :: vtmp(:, :)
      character(len=nlen_label_str), allocatable :: itmp(:)
      asc = .true.
      if (present(ascending)) asc = ascending
      if (.not. allocated(self%values)) return
      n = nrow(self)
      if (n <= 1) return
      jcol = self%col_pos(by)
      call argsort_real_str(self%values(:, jcol), perm, asc)
      itmp = self%index(perm)
      self%index = itmp
      allocate (vtmp(n, ncol(self)))
      vtmp = self%values(perm, :)
      self%values = vtmp
   end subroutine sort_values_str

   pure function subtract_df_df_str(a, b) result(c)
      type(DataFrame_str_index), intent(in) :: a, b
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values - b%values
   end function subtract_df_df_str

   pure function subtract_df_scalar_str(a, s) result(c)
      type(DataFrame_str_index), intent(in) :: a
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values - s
   end function subtract_df_scalar_str

   pure function subtract_scalar_df_str(s, a) result(c)
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index), intent(in) :: a
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = s - a%values
   end function subtract_scalar_df_str

   pure function add_df_df_str(a, b) result(c)
      type(DataFrame_str_index), intent(in) :: a, b
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values + b%values
   end function add_df_df_str

   pure function add_df_scalar_str(a, s) result(c)
      type(DataFrame_str_index), intent(in) :: a
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values + s
   end function add_df_scalar_str

   pure function add_scalar_df_str(s, a) result(c)
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index), intent(in) :: a
      type(DataFrame_str_index) :: c
      c = add_df_scalar_str(a, s)
   end function add_scalar_df_str

   pure function multiply_df_df_str(a, b) result(c)
      type(DataFrame_str_index), intent(in) :: a, b
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values*b%values
   end function multiply_df_df_str

   pure function multiply_df_scalar_str(a, s) result(c)
      type(DataFrame_str_index), intent(in) :: a
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values*s
   end function multiply_df_scalar_str

   pure function multiply_scalar_df_str(s, a) result(c)
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index), intent(in) :: a
      type(DataFrame_str_index) :: c
      c = multiply_df_scalar_str(a, s)
   end function multiply_scalar_df_str

   pure function divide_df_df_str(a, b) result(c)
      type(DataFrame_str_index), intent(in) :: a, b
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values/b%values
   end function divide_df_df_str

   pure function divide_df_scalar_str(a, s) result(c)
      type(DataFrame_str_index), intent(in) :: a
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = a%values/s
   end function divide_df_scalar_str

   pure function divide_scalar_df_str(s, a) result(c)
      real(kind=dp), intent(in) :: s
      type(DataFrame_str_index), intent(in) :: a
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = s/a%values
   end function divide_scalar_df_str

   pure function log_df_str(a) result(c)
      type(DataFrame_str_index), intent(in) :: a
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = log(a%values)
   end function log_df_str

   pure function exp_df_str(a) result(c)
      type(DataFrame_str_index), intent(in) :: a
      type(DataFrame_str_index) :: c
      c%index = a%index
      c%columns = a%columns
      c%values = exp(a%values)
   end function exp_df_str

   ! pandas-style print(df): index label + one right-justified column per
   ! %columns entry (read at runtime, not baked into a literal format string
   ! per call site -- see xp2f.py's _emit_pandas_df_print, which used to
   ! inline this whole block at every print(df) call).
   subroutine display_str_index(self, ndigits)
      class(DataFrame_str_index), intent(in) :: self
      integer, intent(in), optional :: ndigits
      integer :: nd, col_width, idx_width, n_cols, pdf_n, pdf_i
      character(len=:), allocatable :: header_fmt, row_fmt, dots_fmt
      character(len=32) :: nc_str, cw_str, iw_str, nd_str

      nd = 6
      if (present(ndigits)) nd = ndigits
      col_width = max(10, nd + 8)
      idx_width = 24
      n_cols = size(self%columns)
      pdf_n = nrow(self)

      write (nc_str, '(I0)') n_cols
      write (cw_str, '(I0)') col_width
      write (iw_str, '(I0)') idx_width
      write (nd_str, '(I0)') nd

      header_fmt = '(A'//trim(iw_str)//','//trim(nc_str)//'A'//trim(cw_str)//')'
      row_fmt = '(A'//trim(iw_str)//','//trim(nc_str)//'F'//trim(cw_str)//'.'//trim(nd_str)//')'
      dots_fmt = '(A'//trim(iw_str)//','//trim(nc_str)//'A'//trim(cw_str)//')'

      write (*, header_fmt) '', (trim(self%columns(pdf_i)), pdf_i=1, n_cols)
      if (pdf_n <= 10) then
         do pdf_i = 1, pdf_n
            write (*, row_fmt) trim(self%index(pdf_i)), self%values(pdf_i, :)
         end do
      else
         do pdf_i = 1, 5
            write (*, row_fmt) trim(self%index(pdf_i)), self%values(pdf_i, :)
         end do
         write (*, dots_fmt) '...', ('...', pdf_i=1, n_cols)
         do pdf_i = pdf_n - 4, pdf_n
            write (*, row_fmt) trim(self%index(pdf_i)), self%values(pdf_i, :)
         end do
      end if
      write (*, *)
      write (*, '(A,I0,A,I0,A)') '[', pdf_n, ' rows x ', n_cols, ' columns]'
   end subroutine display_str_index

end module dataframe_str_index_mod
